name: Build demo

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Setup Deno environment
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Build site
        run: deno task build
      - name: Debug project and token
        run: |
          echo "Project: xhjblog"
          echo "Token: ${{ secrets.DENO_DEPLOY_TOKEN }}"

      - name: Deploy to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: xhjblog
          import-map: "./deno.json"
          entrypoint: serve.ts
